Docs for next ver 2.0
flood-io/element pull request #374
Opened 2020-12-03 13:22 UTC by sonnguyenmau

2020-12-04 08:40 UTC, HieuLeKMS commented on packages/docs/versioned_docs/version-1.0/guides/CLI.md
> +  - `--loop-count` Override the loopCount setting in the test script `[number]`
In Element 1.0 `loop-count` has its value default to 1

2020-12-04 08:55 UTC, honglax commented on packages/docs/docs/start/install.md
> +element --version
You should use extension **Remark** to beautify **the MD files** instead of using **prettier** to avoid the duplication.

2020-12-08 02:38 UTC, honglax commented on packages/cli/src/cmd/run.ts
>  }
This is the code from Element version 1.4. Please don't edit this file at this PR and make another branch from Element@Canary to edit it.

2021-01-12 10:40 UTC, terryytran requested changes

2021-01-12 10:40 UTC, terryytran commented on packages/docs/docs/guides/CLI.md
> +	- `--browser` Specify the browser type used to run the test, using one of `'chromium'` (default), `'firefox'` or `'webkit'`.
- `--browser` Specify the browser type used to run the test, using either `'chromium'` (default), `'firefox'` or `'webkit'`.

2021-01-25 09:20 UTC, honglax commented
Close due to duplicate with [PR#408](https://github.com/flood-io/element/pull/408)

2021-01-25 09:20 UTC, closed without merging