[Element 2.0] Ready to release element 2.0 to master
flood-io/element pull request #421
Opened 2021-02-03 09:47 UTC by honglax

2021-02-04 03:46 UTC, HieuLeKMS commented on packages/core/package.json
> +		"@types/puppeteer": "^2.0.1",
Please help me remove this as we're not using puppeteer anymore

2021-02-04 06:29 UTC, honglax commented on packages/core/package.json
> +		"@types/puppeteer": "^2.0.1",
Resolved

2021-02-10 01:02 UTC, nick-flood requested changes
Its hard with such a large PR to really dig in to the nitty gritty, but I'm sure there were reviews at each merge from smaller branches.

That said, I noticed some things that may need a look at before merge.

2021-02-11 04:29 UTC, ivanvanderbyl requested changes

2021-02-14 23:48 UTC, nick-flood commented
Could we also update any documentation needed. For example, adding a short description to the new packages on https://github.com/flood-io/element/blob/master/DEVELOPMENT.md

2021-02-15 05:02 UTC, nick-flood requested changes

2021-02-15 05:02 UTC, nick-flood commented on tsconfig.json
> +      "@flood/element-*": [
`@flood/element-report` maps to `packages/report/index.ts` not `packages/report/src/index.ts`. Not sure why its not spouting errors on build (perhaps its pulling from local node_modules instead), but should we add it as an explicit case?

2021-02-15 15:29 UTC, HieuLeKMS commented on packages/cli/src/cmd/run.ts
> +		if (args.export) {
I didn't use the main compiler because I want to avoid changing it, but I need to load some SCSS files. Maybe I'll move the compilation part to a new file and import it here

2021-02-15 15:51 UTC, HieuLeKMS commented on packages/cli/templates/report/script.ts
> +    <div class="execution-info">
We considered using React or some other libraries to make the report, but that might affect the report's bundle size, the time to compile. That might also affect Element on the whole because we would add a new subproject, and a bunch of new packages. So we went with using TypeScript and SCSS, and compile the report using Webpack. If you have a better approach, then please let us know.

2021-02-18 01:42 UTC, honglax commented on lerna.json
> +	"version": "2.0.0-canary.36",
Lerna will auto bump version from `2.0.0-canary.36` to `2.0.0`
FYI https://github.com/lerna/lerna/tree/main/commands/version#--conventional-graduate

2021-02-18 01:45 UTC, honglax commented on packages/core/src/page/ElementHandle.spec.ts
> +	test.skip('findElements()', async () => {
There was a bug of `ElementHandle.findElements()` when we using Playwright < v1.8.0. I've reported it [here](https://github.com/microsoft/playwright/issues/4985)  and it is fixed on Playwright v1.8. Hence, I'm going to remove `.skip`.

2021-02-18 02:03 UTC, honglax commented on package.json
> +	"version": "2.0.0",
The version of `package.json` is auto bumped by Lerna. Same as my below comment.

2021-02-18 02:09 UTC, honglax commented on packages/core/src/page/ElementHandle.spec.ts
> +	test.skip('findElements()', async () => {
Resolved.

2021-02-18 02:24 UTC, phileba commented on packages/core/src/ElementOption.ts
> +	// TODO make this more reliable on linux
It already exists from element 1.3 but we have no time to take a look at this. We will have a plan to do this in the future

2021-02-18 02:25 UTC, phileba commented on packages/core/src/ElementResult.ts
> +		const pkg = require(join(findRoot(__dirname), 'package.json'))
@honglax can we try with `fs.readFile`?

2021-02-18 02:28 UTC, phileba commented on packages/core/src/page/conditions/FrameCondition.ts
> -	// public async waitFor(frame: Frame, page: Page): Promise<Frame | Error> {
it seems the commented code was removed

2021-02-18 02:29 UTC, honglax commented on packages/core/src/page/conditions/FrameCondition.ts
> -	// public async waitFor(frame: Frame, page: Page): Promise<Frame | Error> {
The function `waitFor()` has been moved to below `waitForEvent()`.

2021-02-18 02:29 UTC, phileba commented on packages/core/src/runtime/Browser.ts
> +			 * need to implement clear cache for firefox and safari
@terryytran please help us to check this 🙏

2021-02-18 02:32 UTC, phileba commented on packages/core/src/runtime/Browser.ts
> +		 * playwright does not have method bringtoFront()
the latest version of playwright already supported this method https://playwright.dev/docs/api/class-page?_highlight=bringto#pagebringtofront, so we should bring this method back.

2021-02-18 02:34 UTC, phileba commented on packages/core/src/runtime/EvaluatedScript.spec.ts
> +	// TODO move to Test.spec ?
yep, we should remove this, @honglax please go ahead :D

2021-02-18 02:34 UTC, phileba commented on packages/core/src/runtime/EvaluatedScript.spec.ts
> +			// await vm.execute(puppeteer)
yep, we do

2021-02-18 02:39 UTC, phileba commented on packages/core/src/test-script/WebpackCompiler.ts
> +	// maybeLiftError?(error: Error): Error {}
we already have `liftError` method, so I think we should remove this one.

2021-02-18 02:41 UTC, phileba commented on packages/flood-runner/src/Grid.ts
> +		browser: 'chromium',
This is just the default value, if the user wants to run their script with chrome, set `chrome` in the setting or via CLI `--browser chrome`.

2021-02-18 04:42 UTC, honglax commented on packages/core/src/runtime/Browser.ts
> +		 * playwright does not have method bringtoFront()
Resolved

2021-02-18 04:42 UTC, honglax commented on packages/core/scripts/docs/preParseIndex.ts
> -		// debug('node', ts.Debug.showSyntaxKind(node))
Resolved

2021-02-18 04:43 UTC, honglax commented on packages/core/src/runtime/EvaluatedScript.spec.ts
> +	// TODO move to Test.spec ?
Resolved

2021-02-18 04:43 UTC, honglax commented on packages/core/src/runtime/EvaluatedScript.spec.ts
> +			// await vm.execute(puppeteer)
Resolved

2021-02-18 04:44 UTC, honglax commented on packages/core/src/test-script/WebpackCompiler.ts
> +	// maybeLiftError?(error: Error): Error {}
Resolved

2021-02-18 04:45 UTC, honglax commented on packages/core/src/test-script/WebpackCompiler.ts
> +		// writeFileSync(join(this.scriptRoot, 'bundle.js.map'), this.sourceMap, {
Resolved

2021-02-18 04:45 UTC, honglax commented on packages/core/src/test-script/WebpackCompiler.ts
> +				// wrapCodeInModuleWrapper(this.source),
Resolved

2021-02-18 05:03 UTC, HieuLeKMS commented on packages/core/src/ElementResult.ts
> +		const pkg = require(join(findRoot(__dirname), 'package.json'))
`require` reads and caches the file, following calls return the result from cache. And I don't think there're any benefits from changing all those `require` to `fs.readFile`, are there?

2021-02-22 02:57 UTC, nick-flood approved these changes

2021-02-23 16:24 UTC, HieuLeKMS commented on packages/cli/src/cmd/run.ts
> +		if (args.export) {
@ivanvanderbyl  I moved the compile step out of `run`'s handler, are there anything else you want us to change?

2021-02-23 16:24 UTC, HieuLeKMS commented on packages/cli/templates/report/script.ts
> +    <div class="execution-info">
@ivanvanderbyl If you're okay with this, please approve so we can get this merged

2021-03-04 01:39 UTC, ivan-flood requested changes

2021-03-04 01:39 UTC, ivan-flood commented on packages/cli/templates/element.config.js
> +		testPathMatch: ['./*.ts'],
This is a bad idea as a default as it means it would match everything in a typescript project, which we don't want. It needs a unique suffix, which is why .perf.ts was chosen.

2021-03-04 01:41 UTC, honglax commented on packages/cli/templates/element.config.js
> +		testPathMatch: ['./*.ts'],
Got it.

2021-03-04 01:57 UTC, ivan-flood requested changes

2021-03-04 01:57 UTC, ivan-flood commented on packages/core/src/driver/Playwright.ts
> +	if (browserType === 'chrome') {
This seems like a bad idea, we need to support Chrome stable to get access to proprietary codecs for supporting video playback, if we always force it back to chromium this will silently fail.

2021-03-04 02:26 UTC, honglax commented on packages/cli/templates/element.config.js
> +		testPathMatch: ['./*.ts'],
I've created [this PR](https://github.com/flood-io/element/pull/443) to resolve your suggestion. Please take a look at this.

2021-03-04 02:45 UTC, phileba commented on packages/core/src/driver/Playwright.ts
> +	if (browserType === 'chrome') {
I'm not sure about the video playback here, this function is using for running multiple users locally. In the past, we already supported 3 kinds which bundled in playwright are `chromium, firefox, webkit`. We just add chrome stable into this list a few days ago but we have an issue with chrome https://github.com/microsoft/playwright/issues/5327. So I think we should keep supporting 3 kinds of bundled browsers of Playwright.

2021-03-04 02:57 UTC, ivan-flood commented on packages/core/src/driver/Playwright.ts
> +	if (browserType === 'chrome') {
This looks like a breaking change, I mean, I can't see how this would work in production, single or multiple user mode

2021-03-04 03:04 UTC, phileba commented on packages/core/src/driver/Playwright.ts
> +	if (browserType === 'chrome') {
Hi Ivan, this feature support running multiple users locally, not in production. we can trigger this feature by the setting:
```
export const settings: TestSettings = {
  stages: [
    {
      duration: '10m',
      target: 3
    }
  ]
}
```
we have a `scheduler` package to do this thing. Firstly we need to start a browser server, then it depends on the number of targets, we connect to the `wsEndpoint` to init the client browser.
So this feature only runs locally. we ignore this setting when running in production.

2021-03-04 03:08 UTC, ivan-flood commented on packages/core/src/driver/Playwright.ts
> +	if (browserType === 'chrome') {
Okay, I see. Cool.

2021-03-04 03:27 UTC, ivan-flood approved these changes

2021-03-04 03:32 UTC, ivanvanderbyl approved these changes

2021-03-04 04:27 UTC, merged