[recorder] Recorder docs
flood-io/element pull request #439
Opened 2021-03-02 02:57 UTC by terryytran

2021-03-08 06:10 UTC, phieutran approved these changes
The page's content looks good to me

2021-03-08 09:22 UTC, HieuLeKMS commented on packages/docs/recorderDocs/Actions.md
> +If you'd like to change the selected text, you'll need to drag-select the new text on the page and remove the old action.
This is not changing the selected text, this is removing the old action and create a new one. And I think `**Editable:** No` above makes it clear enough that you cannot edit the text and have to create a new action
```suggestion
```

2021-03-08 14:32 UTC, HieuLeKMS commented on packages/docs/recorderDocs/RecordScenario.mdx
> +1. Hover on the action, then click `...` icon > `Move cursor before` or `Move cursor after`. The red line (aka. the cursor) will be moved to the corresponding position.
```suggestion
1. Hover on the action, then click `...` icon > `Move cursor before` or `Move cursor after`. The red line (aka the cursor) will be moved to the corresponding position.
```

2021-03-08 14:32 UTC, HieuLeKMS commented on packages/docs/sidebarsRecorder.js
> +}
```suggestion
}

```

2021-03-08 14:32 UTC, HieuLeKMS commented on packages/docs/tsconfig.json
> +}
```suggestion
}

```

2021-03-09 07:25 UTC, terryytran commented on packages/docs/recorderDocs/Actions.md
> +* **Programming actions:** actions to be used for programming purposes, cannot be recorded by interacting with the browser but added from Recorder menus.
@nick-flood Could you please weigh in?

2021-03-09 07:29 UTC, terryytran commented on packages/docs/recorderDocs/Actions.md
> +* **Programming actions:** actions to be used for programming purposes, cannot be recorded by interacting with the browser but added from Recorder menus.
These actions can be added from different menus: Add menu, Action context menu, and Variable menu (not just 1 menu). So I think the word choice is fine. Let's wait for @nick-flood to weigh in.

2021-03-09 07:38 UTC, terryytran commented on packages/docs/recorderDocs/Actions.md
> +  - **Target element:** Element to click on. This can be changed to any visible elements on the page.
Actually, action-specific fields are the major reason I added this chapter to the guide. It acts like a "API reference". Each action is sort of mapped with an API, which takes in arguments (action-specific fields). I'm aware that our UI is pretty self-explanatory but just want to be sure we don't miss out on anything that a user may look for.

@nick-flood your thoughts on this, please?

2021-03-10 01:54 UTC, nick-flood commented on packages/docs/recorderDocs/Actions.md
> +  - **Target element:** Element to click on. This can be changed to any visible elements on the page.
I like it, even if its a bit self explanatory, the more the merrier.

2021-03-15 03:18 UTC, nick-flood commented on packages/docs/recorderDocs/Actions.md
> +* **Programming actions:** actions to be used for programming purposes, cannot be recorded by interacting with the browser but added from Recorder menus.
Hmm, @ivanvanderbyl might have something in mind here

2021-03-15 05:47 UTC, ivanvanderbyl requested changes
The docs look to cover all the core concepts. Please correct the typos and grammar before merging. If you don't already have access to Grammarly, please ping me for a license.

2021-03-15 05:47 UTC, ivanvanderbyl commented on packages/docs/recorderDocs/Actions.md
> +- **Action type:** Can not be changed
Fix typo

2021-03-15 05:47 UTC, ivanvanderbyl commented on packages/docs/recorderDocs/Actions.md
> +- **Action type:** Can not be changed
Typo

2021-03-15 05:47 UTC, ivanvanderbyl commented on packages/docs/recorderDocs/Actions.md
> +- **Action type:** Can not be changed
Typo

2021-03-15 05:47 UTC, ivanvanderbyl commented on packages/docs/recorderDocs/Actions.md
> +  - **Target element:** The text area to type into. This can be changed to any text areas on the page.
Grammar

2021-03-15 05:47 UTC, ivanvanderbyl commented on packages/docs/recorderDocs/AddAssert.mdx
> +Element Recorder supports different common methods for assertion including:
Grammar

2021-04-05 04:19 UTC, HieuLeKMS approved these changes

2021-04-05 04:28 UTC, merged